/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         sessionId: "sessionId"
 *     }
 */
export interface BrowserCloseRequest {
    sessionId: string;
}
