/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         schema: "schema",
 *         sessionId: "sessionId"
 *     }
 */
export interface BrowserExtractRequest {
    url?: string;
    pageId?: string;
    schema: string;
    sessionId: string;
}
