/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "../../../..";

/**
 * @example
 *     {
 *         prompt: "prompt",
 *         sessionId: "sessionId"
 *     }
 */
export interface BrowserActRequest {
    url?: string;
    pageId?: string;
    prompt: string;
    formValues?: Bytebot.FormValue[];
    sessionId: string;
}
