/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "../../../..";

/**
 * @example
 *     {
 *         url: "url",
 *         html: "html",
 *         prompt: "prompt"
 *     }
 */
export interface ActRequest {
    url: string;
    html: string;
    prompt: string;
    formValues?: Bytebot.FormValue[];
    sessionId?: string;
}
