/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "url",
 *         html: "html",
 *         schema: "schema"
 *     }
 */
export interface ExtractRequest {
    url: string;
    html: string;
    schema: string;
    batchId?: string;
}
