/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "string",
 *         html: "string",
 *         prompt: "string"
 *     }
 */
export interface ActionRequest {
    /** The URL of the page to perform actions on */
    url: string;
    /** HTML content */
    html: string;
    /** Prompt for generating actions */
    prompt: string;
}
