/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export type ActionDetailParameters =
    | Bytebot.ActionDetailParameters.CopyAttribute
    | Bytebot.ActionDetailParameters.AssignAttribute
    | Bytebot.ActionDetailParameters.ExtractTable;

export declare namespace ActionDetailParameters {
    interface CopyAttribute extends Bytebot.CopyAttributeParameters {
        actionType: "CopyAttribute";
    }

    interface AssignAttribute extends Bytebot.AssignAttributeParameters {
        actionType: "AssignAttribute";
    }

    interface ExtractTable extends Bytebot.ExtractTableParameters {
        actionType: "ExtractTable";
    }
}
