/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The result of the action, which can be null, a string, or an array of dictionaries with string keys and values that are either strings or null
 */
export type ActionDetailResult = string | Record<string, string | undefined>[];
