/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface ActionResponse {
    /** List of generated actions */
    actions?: Bytebot.ActionDetail[];
    /** Error message if any */
    error?: string;
}
