/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ActionDetailActionType = "CopyAttribute" | "AssignAttribute" | "Click" | "CopyText" | "ExtractTable";

export const ActionDetailActionType = {
    CopyAttribute: "CopyAttribute",
    AssignAttribute: "AssignAttribute",
    Click: "Click",
    CopyText: "CopyText",
    ExtractTable: "ExtractTable",
} as const;
