/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssignAttributeParameters {
    /** The name of the attribute to assign */
    attribute: string;
    /** The value to assign to the attribute */
    value: string;
}
