/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export type BrowserExtractResponseAction =
    | Bytebot.BrowserExtractResponseAction.CopyAttribute
    | Bytebot.BrowserExtractResponseAction.CopyText
    | Bytebot.BrowserExtractResponseAction.ExtractTable;

export declare namespace BrowserExtractResponseAction {
    interface CopyAttribute extends Bytebot.CopyAttributeBrowserAction {
        type: "CopyAttribute";
    }

    interface CopyText extends Bytebot.CopyTextBrowserAction {
        type: "CopyText";
    }

    interface ExtractTable extends Bytebot.ExtractTableBrowserAction {
        type: "ExtractTable";
    }
}
