/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BrowserStatusResponse {
    /** The session ID */
    sessionId?: string;
    /** The status of the session */
    status?: string;
    /** The timestamp of the last request */
    lastRequestTimestamp?: string;
    /** The number of requests made */
    requestCount?: number;
}
