/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface BrowserActResponse {
    pages?: Bytebot.BrowserPage[];
    actions?: Bytebot.BrowserActResponseActionsItem[];
    error?: string;
}
