/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface CopyAttributeBrowserAction extends Bytebot.BrowserActionBase {
    attribute: string;
}
