/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface ExtractResponse {
    requestId?: string;
    action?: Bytebot.ExtractResponseAction;
    error?: string;
}
