/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface ExtractTableParameters {
    /** An array of columns to be copied into a table */
    columns?: Bytebot.TableColumn[];
}
