/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface ExtractTableActionDetail extends Bytebot.ActionDetailBase {
    columns: Bytebot.TableColumn[];
}
