/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExtractSchemaType = "Text" | "Attribute" | "Table";

export const ExtractSchemaType = {
    Text: "Text",
    Attribute: "Attribute",
    Table: "Table",
} as const;
