/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export type ExtractTableColumnBrowserActionAction =
    | Bytebot.ExtractTableColumnBrowserActionAction.CopyAttribute
    | Bytebot.ExtractTableColumnBrowserActionAction.CopyText;

export declare namespace ExtractTableColumnBrowserActionAction {
    interface CopyAttribute extends Bytebot.CopyAttributeBrowserAction {
        type: "CopyAttribute";
    }

    interface CopyText extends Bytebot.CopyTextBrowserAction {
        type: "CopyText";
    }
}
