/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface TableColumn {
    /** The name of the attribute to extract */
    actionType: Bytebot.TableColumnActionType;
    parameters?: Bytebot.TableColumnParameters;
    /** Name of the column */
    name: string;
    /** The XPath to the element(s) from which the column is to be copied */
    xpath: string;
}
