/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export type TableColumnParameters = Bytebot.TableColumnParameters.CopyAttribute;

export declare namespace TableColumnParameters {
    interface CopyAttribute extends Bytebot.CopyAttributeParameters {
        actionType: "CopyAttribute";
    }
}
