/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export interface TableColumnCopyAttribute extends Bytebot.CopyAttributeActionDetail {
    name: string;
}
