/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Bytebot from "..";

export type TableColumn = Bytebot.TableColumn.CopyAttribute | Bytebot.TableColumn.CopyText;

export declare namespace TableColumn {
    interface CopyAttribute extends Bytebot.TableColumnCopyAttribute {
        actionType: "CopyAttribute";
    }

    interface CopyText extends Bytebot.TableColumnCopyText {
        actionType: "CopyText";
    }
}
