/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The name of the attribute to extract
 */
export type TableColumnActionType = "CopyAttribute" | "CopyText";

export const TableColumnActionType = {
    CopyAttribute: "CopyAttribute",
    CopyText: "CopyText",
} as const;
