/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Browsers } from "./api/resources/browsers/client/Client";
import { Requests } from "./api/resources/requests/client/Client";

export declare namespace BytebotClient {
    interface Options {
        environment?: core.Supplier<environments.BytebotEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class BytebotClient {
    constructor(protected readonly _options: BytebotClient.Options) {}

    protected _browsers: Browsers | undefined;

    public get browsers(): Browsers {
        return (this._browsers ??= new Browsers(this._options));
    }

    protected _requests: Requests | undefined;

    public get requests(): Requests {
        return (this._requests ??= new Requests(this._options));
    }
}
