/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Actions } from "./api/resources/actions/client/Client";

export declare namespace BytebotClient {
    interface Options {
        environment?: core.Supplier<environments.BytebotEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class BytebotClient {
    constructor(protected readonly _options: BytebotClient.Options) {}

    protected _actions: Actions | undefined;

    public get actions(): Actions {
        return (this._actions ??= new Actions(this._options));
    }
}
