/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const BytebotEnvironment = {
    Default: "https://api.bytebot.ai",
} as const;

export type BytebotEnvironment = typeof BytebotEnvironment.Default;
